[package]
name = "tsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
nom = "7.1.3"
pico-args = "0.5.0"
static_assertions = "1.1.0"
