name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**.rs"
      - "**Cargo.**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-llvm-cov

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --all-targets --all --all-features

      - name: Create test files
        working-directory: ./lib/tests/files
        continue-on-error: true
        run: |
          python generate_big.py --name "big_smaller.tsql" --tables 1000 --fields 500
          python generate_big.py --name "big_170mb.tsql" --tables 4000 --fields 1000

      - name: Test
        run: cargo nextest run --all-features --all

      - name: cargo llvm-cov
        run: |
          rm -r ./lib/tests  
          cargo llvm-cov --locked --all --all-features --lcov --output-path lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
